<?php

/**
 * implementation of hook_menu().
 */
function cil_menu() {
  $items['admin/settings/cil'] = array(
    'title' => 'cil',
    'description' => 'Configure cil integration',
    'page callback' => 'cil_admin_page',
    'file' => 'cil.admin.inc',
    'access arguments' => array('administer cil'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/** 
 * Implementation of hook_perm().
 */
function cil_perm() {
  return  array('administer cil');
}

function cil_get($id) {
  return db_fetch_object(db_query("SELECT * FROM {cil_repos} WHERE cil_repo_id=%d", $id));
}